spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false

  data:
    redis:
      host: localhost
      port: 6379

cloudinary:
  url: cloudinary://891526691911467:TnwTqA61t4ZiVvnWt8h0iQVZnII@ddoesja29

jwt:
  secret: "dGVzdC1zZWNyZXQta2V5LWZvci10ZXN0aW5nLXB1cnBvc2VzLW9ubHk="
  expiration: 3600000

logging:
  level:
    root: INFO
